- backends/client.go
- backends/zookeeper/client.go
- config.go
- docs/quick-start-guide.md
- integration/zookeeper/main.go
- integration/zookeeper/test.json
- integration/zookeeper/test.sh
* watch is not yet supported - see backends/zookeeper/client.go for details
* integration should work
* add a simple example in quickstart guide
* exit if watch is enabled when zookeeper is defined as backend
Tested with go 1.4
> Add simple zookeeper support

- docs/templates.md
- resource/template/template_funcs.go
- resource/template/template_test.go
I added support for getting values for properties inside a JSON value.
I find it useful when I store large JSON structures.
Example from `docs/templates.md`
```
{{jsonGet (getv "/test/data/") "animals.0.name"}}
{{ $animal := jsonGet (getv "/test/data/") "animals.1"}}
type: {{ $animal.type }}
name: {{ $animal.name }}
{{range jsonGet (getv "/test/data/") "animals.*.name"}}
{{.}}
{{end}}
```
> Added jsonGet support to template_funcs

- integration/consul/test.sh
- integration/etcd/test.sh
- integration/redis/test.sh
- integration/zookeeper/test.sh
also includes an integration test for redis to ensure it fails when `-watch` is present
> general integration test nitpicks

- backends/etcd/client.go
Since the event history of etcd uses an (incorrectly implemented) cyclical buffer to store the event history, the history will periodically be wiped. When this happens, confd will go into an infinite loop with the following error
```
/opt/confd[20]: ERROR 401: The event in requested index is outdated and cleared (the requested history has been cleared [21424125/20199907]
```
The following code can be used to demonstrate the bug:
```go
package main
import (
"fmt"
"time"
"github.com/coreos/go-etcd/etcd"
)
func main() {
client := etcd.NewClient([]string{"http://127.0.0.1:4001"})
var lastIndex uint64 = 0
for {
resp, err := client.Watch("/test", lastIndex, true, nil, nil)
if err != nil {
fmt.Printf("%#v\n", err)
time.Sleep(1000 * time.Millisecond)
// lastIndex = 0 // Uncomment to fix the error …
```
> Fix "The event in requested index is outdated and cleared" error

- .travis.yml
`tip` and `1.4` may return the same build right now (using [`gimme`](https://github.com/meatballhat/gimme)), but this future-proofs the automated testing a bit. See http://docs.travis-ci.com/user/languages/go/#Specifying-a-Go-version-to-use for details.
> add go 1.4 to travis.ci version matrix

- confd.go
Support enabling watch from either the command line or the config file.
This fixes #208.
> Enable watch from the config file

- config.go
In recent versions of confd, this file is not necessary to run confd
as seen in the integration tests. This switches the log to debug as it's
still interesting information, but it's not necessary to log if we've
supplied the correct flagset to run confd without a config file.
> log that we're skipping config file to debug

- install
This allows users to install confd to somewhere else rather than /usr/local/bin by overriding the envvar.
e.g.
```
$ BIN_DIR=~/bin ./install
Installing confd to /home/bacongobbler/bin/confd...
```
> allow override of BIN_DIR

- config.go
This allows confd to take cert-related configuration from environment variables. Could be expanded to handle all of the configuration variables.
> client cert config from environment variables

- resource/template/resource.go
We want to see the command output whether the command exited in error or
not. Otherwise it's very difficult to debug why your command is failing.
> Log command output on error

- resource/template/resource.go
Currently confd prints a stacktrace and exits when there is an error
processing a template.
Fix this issue by printing a error message instead of crashing. confd
will now resume processing other template resources.
Fixes #284
> template: don't crash on template error

- src/github.com/kelseyhightower/confd/backends/dynamodb/client.go
Confd 0.10.0 with a dynamodb backed always seems to fail with a  `FATAL EmptyStaticCreds: static credentials are empty error`.  Tried to set the credentials with both environmental variables and with a config file with no success. 
This seems to be because of [this line](https://github.com/kelseyhightower/confd/blob/master/src/github.com/kelseyhightower/confd/backends/dynamodb/client.go#L23) which only sets dummy, empty credentials. 
This patch replaces that with a [chain provider](https://github.com/kelseyhightower/confd/blob/master/vendor/src/github.com/awslabs/aws-sdk-go/aws/credentials/chain_provider.go) which looks at the [AWS environmental variables](http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-environment) and at [EC2 provided …
> Load AWS credentials through a provider chain

- docs/configuration-guide.md
Passed by and noticed that the old link redirects to the projects github home page.
> link to the right command-line-flags doc

- .travis.yml
- docs/quick-start-guide.md
- integration/rancher/test.sh
- src/github.com/kelseyhightower/confd/backends/client.go
- src/github.com/kelseyhightower/confd/backends/rancher/client.go
- src/github.com/kelseyhightower/confd/config.go
Inside a Rancher Container Service environment a user has access to a container metadata service that is similar to AWS style metadata. With this backend users can consume the data with confd.
This PR has the backend, updated docs, and integration tests. Hopefully I covered everything, but if not let me know and will add whatever is needed.
Thanks!
> Add Rancher Metadata backend

- src/github.com/kelseyhightower/confd/backends/env/client.go
- src/github.com/kelseyhightower/confd/confd.go
- src/github.com/kelseyhightower/confd/resource/template/processor.go
When setting up a new installation running in `onetime` mode and using the `env` backend I ran into a number of issues that produced no error or debugging output. I ended up modifying the code to tell me what's happening. This PR add some more logging in areas where you are currently blind and hopefully will benefit anyone else facing a similar issue.
> Add more debugging output for onetime and env.

- docs/command-line-flags.md
- docs/configuration-guide.md
- src/github.com/kelseyhightower/confd/config.go
- src/github.com/kelseyhightower/confd/resource/template/resource.go
This pull request adds a -sync-only flag, for sync configuration only, do not need run check_cmd and reload_cmd.
> add -sync-only flag

- .dockerignore
- Dockerfile
- Dockerfile.build.alpine
- docs/installation.md
- docs/templates.md
- src/github.com/kelseyhightower/confd/resource/template/template_funcs.go
- src/github.com/kelseyhightower/confd/resource/template/template_test.go
PR adds IP lookup function for templates. SImilar to #323 with small but significant difference. This version sorts the IP list so that unnecessary config reloads can be avoided. 
As we are using this on Docker and using Alpine as our base image there's also builder image for Alpine package building.
> IP dns resolving function for templates

- docs/tomcat-sample.md
Found some spelling mistakes -
`usally` > `usually`
`espcially` > `especially`
`envionment` > `environment`
Also replaced `An` with `A`
> Fix typos in docs/tomcat-sample.md

- docs/template-resources.md
only uid and gid are implemented right now so I've changed the doc accordingly
> Fix doc to use UID/GID instead of owner/group

- Dockerfile.build.alpine
- docs/installation.md
the old Dockerfile was no longer working because of the switch to the go 1.6 vendoring support in favor of gb.
> updated Dockerfile.build.alpine

- resource/template/template_funcs.go
extended the `getenv` template function to allow default values.
useful when you want to have a default value if nothing was supplied, for instance:
`{{ getenv "HOST_IP" "127.0.0.1" }}`
added a new `map` function that allows to create maps inside a template. for instance:
`{{$endpoint := map "name" $name "private_port" $private_port "public_port" $public_port}}`
this is very useful if you have a defined sub-templates and you want to pass multiple values to them.
the idea & code was written by **tux21b** at [stackoverflow](https://stackoverflow.com/questions/18276173/calling-a-template-with-several-pipeline-parameters/18276968#18276968)
> extended getenv & map template functions

- config.go
Without passing `-node`, Vault will panic:
```
panic: runtime error: index out of range
goroutine 1 [running]:
panic(0xb9ece0, 0xc820010040)
/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/kelseyhightower/confd/backends.New(0x0, 0x0, 0x0, 0x0, 0x7fff1a2aee58, 0x5, 0x0, 0x0, 0x0, 0x0, ...)
/Users/kelseyhightower/go/src/github.com/kelseyhightower/confd/backends/client.go:61 +0xbdf
main.main()
/Users/kelseyhightower/go/src/github.com/kelseyhightower/confd/confd.go:27 +0x1f4
```
> Specify default Vault backend node

- Dockerfile.build.alpine
Hi everyone,
I wanted to use the "suppress newlines" feature introduced in Go 1.6 with confd. Turned out, the release binaries uploaded to Github are made with Go 1.5.
The latest, stable(!) Alpine version already ships with Go 1.6, so I thought we should upgrade the builder Dockerfile to use it.
The mentioned feature:
> {{end}} vs. {{- end}} and {{end -}} will suppress unnecessary empty lines in the confd generated output, creating a much human-readable output file.
> Upgrade Dockerfile to use latest stable Alpine which has Go 1.6

- docs/quick-start-guide.md
use right md syntax to fix `valut` title
> Fix typo in quick-start-guide.md

- docs/installation.md
I just wanted to add confd to my webapp container, but am unable to find an alpine apk.  So i found your instructions to do a build using a container.  In my case i would have to build just to get a binary to add to my image with a COPY.  This does it all in place using the new Multi-Stage build process.
> Added instructions for Dockerfile build

- backends/etcd/client.go
I think it is not necessary to run 
```
ctx, cancel := context.WithCancel(context.Background())
cancelRoutine := make(chan bool)
defer close(cancelRoutine)
go func() {
select {
case <-stopChan:
cancel()
case <-cancelRoutine:
return
}
}()
```
all the time in the for loop. 
This will waste resources in the case that keys with a key prefix we don't care about are changed in a high frequency.
I made a few simple changes to the watchPrefix method to improve these behavior.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kelseyhightower/confd/403)
> improved etcd watch support

- src/github.com/kelseyhightower/confd/resource/template/template_funcs.go
No impact on master. No backward compatibility issues.
Just added a few arithmetic operator to the templating engine. I have found the modulus operator very important for confd.
Please consider merging this pull request.
Cheers!
This fixes #343, fixes #576
> Feature new template func add

- backends/rancher/client.go
- config.go
Rancher recently added long polling capabilities to their metadata API.
This commit implements the previously stubbed confd WaitPrefix method.
> Introducing WaitPrefix for the Rancher backend

- build
- confd.go
- version.go
New features may be added to golang template.
If the user want to use the new feature (for example, go 1.6 supports trimming whitespace characters), they have to check the go version that the binary was built with. So I think adding the golang version to the `-version` command's output may be useful.
Signed-off-by: Shijiang Wei mountkin@gmail.com
> add go version and git commit sha1 to version string

- backends/client.go
- backends/consul/client.go
- config.go
- docs/command-line-flags.md
This PR updates the consul client to support the basic authentication.
It should resolve #625.
> Add support for consul BasicAuth

- backends/ssm/client.go
This PR checks the SSM response error string for "ParameterNotFound" and, if found, ignores the error.  Had I been more proficient at golang, I might have checked something more substantial like a status code.   
This is in an effort to fix https://github.com/kelseyhightower/confd/issues/606.
> AWS ssm - don't treat "ParameterNotFound" as a fatal error

- resource/template/resource.go
Currently confd will try to use `/bin/sh` to run the reload_cmd or check_cmd.
This always fails on windows, which is why I changed it to run `cmd /C` instead.
runCommand function originally from https://github.com/kelseyhightower/confd/pull/601
> Added windows cmd support

- backends/zookeeper/client.go
Fixes #656
The zookeeper backend attempts to call nodeWalk with an empty prefix.  Newer
versions of https://github.com/samuel/go-zookeeper/ will validate keys passed
as input parameters and return an error if an empty string is passed.  This
change modifies the logic slightly to handle the case where we want to walk the
nodes of the parent "/" key.
> Don't pass empty prefix to zookeeper nodeWalk

- backends/vault/client.go
[Vault TLS Certificates Auth Method](https://www.vaultproject.io/docs/auth/cert.html)
Authentication type `-auth-type cert`.
If `-client-cert` and `-client-key` are not set or invalid, authentication will fail.
> Vault TLS certificates auth method

- config.go
I've noticed that when using SRV discovery with etcd backend the etcd client complains about unknown protocol with endpoints being just `a.b.c:2379`. Prepending the scheme to the endpoints fixes the issue.
> backend/etcd: add scheme to srv discovered endpoints

- backends/client.go
- backends/config.go
- backends/vault/client.go
- config.go
- docs/command-line-flags.md
As of Vault 0.6.1, App ID is deprecated in favor of [AppRole](https://www.vaultproject.io/docs/auth/approle.html) this PR adds support for this backend authN to confd.
> Add AppRole authN for Vault backend
