kelseyhightower/confd

docs/templates.md

I saw that all of the other template examples had the output, except for the complex one (the one I needed most! :smile:  ). This PR adds the output for the Complex Iteration example.

Add the output for Complex iteration example

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/samuel/go-zookeeper/zk/cluster_test.go
Godeps/_workspace/src/github.com/samuel/go-zookeeper/zk/conn.go
Godeps/_workspace/src/github.com/samuel/go-zookeeper/zk/constants.go
Godeps/_workspace/src/github.com/samuel/go-zookeeper/zk/lock.go
Godeps/_workspace/src/github.com/samuel/go-zookeeper/zk/lock_test.go
Godeps/_workspace/src/github.com/samuel/go-zookeeper/zk/server_help.go
Godeps/_workspace/src/github.com/samuel/go-zookeeper/zk/server_java.go
Godeps/_workspace/src/github.com/samuel/go-zookeeper/zk/structs.go
Godeps/_workspace/src/github.com/samuel/go-zookeeper/zk/structs_test.go
Godeps/_workspace/src/github.com/samuel/go-zookeeper/zk/tracer.go
Godeps/_workspace/src/github.com/samuel/go-zookeeper/zk/util.go
Godeps/_workspace/src/github.com/samuel/go-zookeeper/zk/zk_test.go

The zk godep is missing and CI is currently only passing, because Travis runs `go get` by default, which downloads zk https://travis-ci.org/kelseyhightower/confd/jobs/51791525#L110

Added missing zk godep

---

docs/templates.md
resource/template/template_funcs.go
resource/template/template_test.go

Reverts kelseyhightower/confd#222

Revert "Added jsonGet support to template_funcs"

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/garyburd/redigo/internal/commandinfo.go
Godeps/_workspace/src/github.com/garyburd/redigo/internal/redistest/testdb.go
Godeps/_workspace/src/github.com/garyburd/redigo/redis/conn.go
Godeps/_workspace/src/github.com/garyburd/redigo/redis/conn_test.go
Godeps/_workspace/src/github.com/garyburd/redigo/redis/doc.go
Godeps/_workspace/src/github.com/garyburd/redigo/redis/log.go
Godeps/_workspace/src/github.com/garyburd/redigo/redis/pool.go
Godeps/_workspace/src/github.com/garyburd/redigo/redis/pool_test.go
Godeps/_workspace/src/github.com/garyburd/redigo/redis/pubsub.go
Godeps/_workspace/src/github.com/garyburd/redigo/redis/pubsub_test.go
Godeps/_workspace/src/github.com/garyburd/redigo/redis/redis.go
Godeps/_workspace/src/github.com/garyburd/redigo/redis/reply.go
Godeps/_workspace/src/github.com/garyburd/redigo/redis/reply_test.go
Godeps/_workspace/src/github.com/garyburd/redigo/redis/scan.go
Godeps/_workspace/src/github.com/garyburd/redigo/redis/scan_test.go
Godeps/_workspace/src/github.com/garyburd/redigo/redis/script.go
Godeps/_workspace/src/github.com/garyburd/redigo/redis/script_test.go
Godeps/_workspace/src/github.com/garyburd/redigo/redis/test_test.go
Godeps/_workspace/src/github.com/garyburd/redigo/redis/zpop_example_test.go
backends/client.go
backends/redis/client.go
config.go
integration/redis/test.sh

* watch is not yet supported
* auth and select is not yet support
closes #168

Add simple redis support

---

docs/templates.md

A new pull request for clarifying how to traverse the JSON. It would have helped me out since I didn't read the Go template docs properly. Use it if you like it.

Improved docs for how to use go templates to traverse json

---

docs/templates.md
resource/template/template_funcs.go
resource/template/template_test.go

Add toUpper, toLower support

---

version.go

Better late than never. Closes #240.

bump version to 0.8.0

---

resource/template/processor.go
resource/template/util.go
resource/template/util_test.go

Adding recursive find path when find toml file in cond.d.
Cause in our production, company's all project share one conffile project which's master branch is managed only by OP to make the releasing smoothly.I thought it's a very common for Enterprise Software Development.
In this situation, all the files of tens of project in only on directory, make it looks mass. So hope ours can be in part of.

*feature) add recursive get toml files.

---

.travis.yml
resource/template/util_test.go

bump etcd to v2.0.9 for integration tests

---

CONTRIBUTING.md
MAINTAINERS

please make sure I included everyone :)

Add maintainers file

---

config.go
config_test.go
docs/command-line-flags.md
docs/configuration-guide.md
docs/noop-mode.md
log/log.go

as per the TODO notice I set for myself :)

remove --quiet, --debug and --verbose

---

MAINTAINERS

We've been acquired! https://www.engineyard.com/engine-yard-and-deis

change opdemand emails to engine yard

---

resource/template/template_funcs.go

feat: add strings.Contains support

---

README.md

Confd, you look good with those backends patched up.

Updating README.md to include new backends

---

src/github.com/kelseyhightower/confd/resource/template/template_funcs.go

Add strings.Replace support

---

src/github.com/kelseyhightower/confd/backends/client.go
src/github.com/kelseyhightower/confd/backends/config.go
src/github.com/kelseyhightower/confd/backends/env/client.go
src/github.com/kelseyhightower/confd/backends/stackengine/client.go
src/github.com/kelseyhightower/confd/config.go

Adds simple backend support for StackEngine's built-in kv store.  Uses Authentication Bearer token (auth_token) for API authentication.

Add StackEngine backend support

---

src/github.com/kelseyhightower/confd/config.go

add default node for zookeeper backend

---

src/github.com/kelseyhightower/confd/resource/template/processor.go

Load template resources every interval, so we can dynamically add or change toml files in dir conf.d.

load template resources every interval

---

docs/command-line-flags.md
docs/quick-start-guide.md

Great work with confd! It's super useful, and easy to use.
I've added the necessary documentation on how to use stackengine as a backend into the various documenation files. I'm pretty sure I've updated all the required files, but if I missed something, let me know!
Thanks.

Added documentation for stackengine as a backend

---

src/github.com/kelseyhightower/confd/backends/client.go
src/github.com/kelseyhightower/confd/backends/config.go
src/github.com/kelseyhightower/confd/backends/etcd/client.go
src/github.com/kelseyhightower/confd/config.go

Adding support for etcd 2.1's [authentication](https://github.com/coreos/etcd/blob/master/Documentation/authentication.md)  feature.

Add support for etcd BasicAuth

---

src/github.com/kelseyhightower/confd/backends/redis/client.go

Make the redis client test its connection before each GetValues operation with a
`PING` command. If the connection is dead, try to connect to one of the configured redis nodes. Only performs a single reconnect attempt. For my use case, I can just wait until confd tries to apply configuration templates again.
Fixes #373 as far as I'm concerned.
Weaknesses:
* _nodes are always contacted in the same order_, should probably randomize/hash order or something? 
* _one re-connection attempt for each template, not just once for each time the interval fires_. We'd probably need a more sophisticated backend/client interface to improve on that.
I don't have much experience with go. I'm happy to improve/correct the PR if necessary.

redis: try to recover from closed connections

---

backends/etcd/client.go
resource/template/processor.go

fixed broken etcd watch support

---

docs/templates.md
resource/template/template_funcs.go

Adds support for fetching SRV records and using them in a template. Would go great in conjunction with https://github.com/kelseyhightower/confd/pull/333

Add lookupSRV function.

---

config.go
docs/command-line-flags.md
docs/quick-start-guide.md

I've updated some docs regarding the new etcd backend and -scheme commandline flag

update some docs

---

README.md
docs/quick-start-guide.md

updated the README to include sections with vault

updated README for vault

---

.travis.yml
backends/zookeeper/client.go
config.go
integration/zookeeper/test.sh
integration/zookeeper/zoo.cfg

This pull request adds zookeeper watch support.

zookeeper watch support

---

README.md

PNG looks blurry with DPI scaling.

Use SVG for the build image

---

backends/dynamodb/client.go
integration/dynamodb/test.sh

This fixes #427 and adds a test case to prevent regressions.
PTAL @bacongobbler

Fix DynamoDB credentials handling

---

docs/template-resources.md

Fix typo in template-resources.md

---

.travis.yml

Solves: https://github.com/kelseyhightower/confd/issues/540

Fix travis configuration to use latest dynamoDB binary

---

docs/quick-start-guide.md

Change etcd node port because the official port of etcd is 2379

Change etcd node port because the official port of etcd is 2379

---

backends/redis/client.go
docs/quick-start-guide.md
integration/redis/test.sh

added support to specify a redis database (in the connection string)

---

resource/template/template_funcs.go

Another simple strings function:
- **trimSuffix**

add trimSuffix template function

---

resource/template/fileStat_posix.go
resource/template/fileStat_windows.go
resource/template/resource.go
resource/template/util.go

I've added support for windows.
This is based on #45.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kelseyhightower/confd/434)

Windows support

---

resource/template/template_funcs.go

I have implemented some additional sorting methods so that you can:
- sort by lenght
- reverse the sort results
Example:
```
{{ range $dir := (lsdir "/services" | sortByLength | reverse) }}
...
...
{{ end }}
```
```
{{range (gets "/services/test/*" | sortKVByLength | reverse) }}
key: {{.Key}}
value: {{.Value}}
{{end}}
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kelseyhightower/confd/416)

added some additional text/template sorting methods

---

docs/installation.md

Slightly more descriptive instructions will definitely increase adoption rate

Add further installation instructions

---

Godeps/Godeps.json
vendor/github.com/kelseyhightower/memkv/.travis.yml
vendor/github.com/kelseyhightower/memkv/store.go

Update memkv to v0.1.1

---

integration/etcd/test.sh

* output
```bash
~]$ make integration
(omitted)
curl: (6) Could not resolve host: value=10.0.1.11; Name or service not known
(omitted)
curl: (6) Could not resolve host: value=10.0.1.11; Name or service not known
(omitted)
```

fix(confd): etcd curl err when make integration

---

backends/etcdv3/client.go

@okushchenko Please check code, I have no too much experience on Go.
Closes #615

fix etcdv3 client watch: reuse previous watch to avoid memory leak

---

.travis.yml
Makefile
backends/consul/client.go
integration/confdir/templates/basic.conf.tmpl
integration/confdir/templates/exists-test.conf.tmpl
integration/confdir/templates/iteration.conf.tmpl
integration/consul/test.sh
integration/dynamodb/test.sh
integration/env/test.sh
integration/etcd/test.sh
integration/etcdv3/test.sh
integration/expect/basic.conf
integration/expect/check.sh
integration/expect/exists-test.conf
integration/expect/iteration.conf
integration/file/test.sh
integration/rancher/test.sh
integration/redis/test.sh
integration/ssm/test.sh
integration/vault/test.sh
integration/zookeeper/test.sh

Fix panic during Consul client creation

---

backends/etcdv3/client.go

replace fmt.Println() with log.Debug()

remove fmt.Println

---

docs/templates.md
resource/template/template_funcs.go
resource/template/template_test.go

This fixes #660. Included test case too.

Add atoi function to template funcs and test

---

resource/template/template_funcs.go
resource/template/template_test.go

Add LookupIPV4, LookupIPV6 template functions

---

backends/file/client.go
docs/quick-start-guide.md

Recent Tweets inspired a contribution of documentation. CI failed tangentially so I added a fix for that as well.

add file backend to quick start guide
